# Site Settings
title: DP | Douglas Porto Blog
email: douglasalexandre7@gmail.com
description: "Web Developer | Front End"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://douglasporto.com.br" # the base hostname & protocol for your site
google_analytics: "UA-117260112-1"


# User Settings
username: DouglasPorto
user_description: Web Developer | Front End.
disqus_username: disqus_Y3loMDcVS3

# Social Media
# Remove the item if you don't need it
github_username: douglasporto
facebook_username: dgsapenas
twitter_username: dgsapenas
instagram_username: dgsapenas
linkedin_username: douglas-porto-b754817a
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

collections:
  - projects

# Plugins
gems:
  - jemoji
  
#SKILLS
skill:
  - name: HTML5
    img: html5
  - name: jekyll
    img: jekyll
  - name: WordPress
    img: wordpress
  - name: CSS3
    img: css3
  - name: SASS
    img: sass
  - name: Responsive Web 
    img: responsive
  - name: bootstrap
    img: bootstrap
  - name: Javascript
    img: javascript
  - name: Vue.js
    img: vuejs
  - name: JQuery
    img: jquery
  - name: Node.js
    img: nodejs  
  - name: Gulp.js
    img: gulp  
  - name: PHP
    img: php
  - name: Laravel  
    img: laravel 
  - name: Codeigniter
    img: codeigniter
  - name: Apache
    img: apache
  - name: Git
    img: git
  - name: GitHub 
    img: github
  - name: GitLab 
    img: gitlab
  - name: Linux
    img: linux
  - name: Photoshop
    img: photoshop
# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Quem sou
    url: /quem-sou/
  - title: Contato
    url: /contato/  
  - title: Projetos
    url: /projects/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
